<?php

/*
Plugin Name:  WP PleaseWait
Plugin URI:   https://ngoclb.com/project/wp-please-wait
Description:  Add PleaseWait loading screen to currrent theme
Version:      1.0.3
Author:       Ngoc LB
Author URI:   https://ngoclb.com/
License:      MIT License
*/

if ( ! defined( 'ABSPATH' ) ) {
  die();
}

require 'pleasewait-settings.php';

class WpPleaseWait {

  private static $instance;
  private $options;

  public function __construct()	{
    $this->options = WpPleaseWait_SettingsPage::getInstance()->get_options();
    $this->load_actions();
  }

  /**
   * Singleton instance
   */
  public static function getInstance() {
    if (!self::$instance) {
      self::$instance = new self();
    }
    return self::$instance;
  }

  function load_actions() {
    $hook_name = $this->options['hook_name'];
    // Hook
    add_action( 'wp_enqueue_scripts', array( $this, 'add_styles_scripts' ) );
    add_action( 'wp_head', array( $this, 'add_inline_styles' ) );
    add_action( $hook_name, array( $this, 'add_inline_scripts' ) );
  }

  function add_styles_scripts() {
    wp_enqueue_style( 'spinkit',
      ( $this->options['use_cdn'] ? 'https://cdnjs.cloudflare.com/ajax/libs/spinkit/1.2.5' : WpPleaseWait_SettingsPage::getInstance()->get_assets_url('assets') )
      . '/spinkit.min.css' );
    wp_enqueue_style( 'please-wait-css',
      ( $this->options['use_cdn'] ? 'https://cdnjs.cloudflare.com/ajax/libs/please-wait/0.0.5' : WpPleaseWait_SettingsPage::getInstance()->get_assets_url('assets') )
      . '/please-wait.min.css' );
    wp_enqueue_script( 'please-wait-js',
      ( $this->options['use_cdn'] ? 'https://cdnjs.cloudflare.com/ajax/libs/please-wait/0.0.5' : WpPleaseWait_SettingsPage::getInstance()->get_assets_url('assets') )
     . '/please-wait.min.js', array(), '0.0.5', false );
  }

  function combine_to_oneline($html_css_js, $rm_trailing_space = true) {
    $one_line = str_replace(array("\r\n", "\r", "\n", "\t"), "  ", $html_css_js);
    if ($rm_trailing_space) {
      while (strpos($one_line, "  ") > -1) {
        $one_line = str_replace("  ", " ", $one_line);
      }
    }
    return $one_line;
  }

  function print_plugin_info() {
    $ver = WpPleaseWait_SettingsPage::CURRENT_VERSION;
    $url = WpPleaseWait_SettingsPage::GITHUB_URL;
    echo "<!-- Generated by WP PleaseWait v${ver} - ${url} -->\n";
  }

  function add_inline_styles() {
    $scale_value = $this->options['spinner_scale'];
    $text_color = $this->options['text_color'];
    $css = <<<CSS
    html.pg-loading {
      overflow: hidden;
    }
    body > .inner {
      display: none;
    }
    body.pg-loaded > .inner {
      display: block;
    }
    .pg-loading-screen .pg-loading-html { margin-top:0 }
    .pg-loading-html {
      transform: scale({$scale_value});
      -webkit-transform: scale({$scale_value});
    }
    .pg-loading-html .sk-rect,
    .pg-loading-html .sk-cube,
    .pg-loading-html .sk-circle,
    .pg-loading-html .sk-child { background: {$text_color}}
    .loading-message { color: {$text_color} }
CSS;
    $this->print_plugin_info();
    echo sprintf("<style type='text/css'>%s</style>", $this->combine_to_oneline($css));
  }

  function add_inline_scripts() {
    $template = addslashes_gpc($this->combine_to_oneline($this->options['loading_template']));
    $spinner_style = addslashes_gpc($this->combine_to_oneline($this->options['spinner_styles'][$this->options['spinner_style']]));
    $js = <<<JS
var rootelem = document.querySelector('html'),
  loading_screen = pleaseWait({
  logo: false,
  template: "{$template}",
  backgroundColor: '{$this->options['bg_color']}',
  loadingHtml: "{$spinner_style}",
  onLoadedCallback: function() { setTimeout(function(){rootelem.className = rootelem.className.replace('pg-loading', 'pg-loaded').trim();} , 200); }
});
rootelem.className += ' pg-loading';
function hide_loading_screen() {loading_screen.finish();}
document.addEventListener("DOMContentLoaded", hide_loading_screen);
JS;
    if ($this->options['timeout']) {
      $js .= "setTimeout(hide_loading_screen, {$this->options['timeout']}*1000);";
    }
    $this->print_plugin_info();
    echo sprintf("<script type='text/javascript'>%s</script>", $this->combine_to_oneline($js));
  }
}

WpPleaseWait::getInstance();
